# Generated by Django 4.2.16 on 2024-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gossip',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
